namespace Pro
{
    partial class Register
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Register));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            this.registerUser = new System.Windows.Forms.Panel();
            this.MinBtn = new System.Windows.Forms.PictureBox();
            this.panel1 = new System.Windows.Forms.Panel();
            this.exit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Signup = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.firstNamereg = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.repwordreg = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.pwordreg = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.userNamereg = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lastNamereg = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.fatherNamereg = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.registerUser.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.MinBtn)).BeginInit();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // registerUser
            // 
            this.registerUser.BackColor = System.Drawing.Color.Salmon;
            this.registerUser.Controls.Add(this.MinBtn);
            this.registerUser.Controls.Add(this.panel1);
            this.registerUser.Location = new System.Drawing.Point(-4, -3);
            this.registerUser.Name = "registerUser";
            this.registerUser.Size = new System.Drawing.Size(526, 580);
            this.registerUser.TabIndex = 0;
            this.registerUser.Paint += new System.Windows.Forms.PaintEventHandler(this.registerUser_Paint);
            // 
            // MinBtn
            // 
            this.MinBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.MinBtn.Image = global::Pro.Properties.Resources.minimize1;
            this.MinBtn.Location = new System.Drawing.Point(479, 15);
            this.MinBtn.Name = "MinBtn";
            this.MinBtn.Size = new System.Drawing.Size(34, 36);
            this.MinBtn.TabIndex = 13;
            this.MinBtn.TabStop = false;
            this.MinBtn.Click += new System.EventHandler(this.MinBtn_Click);
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.SlateGray;
            this.panel1.Controls.Add(this.exit);
            this.panel1.Controls.Add(this.Signup);
            this.panel1.Controls.Add(this.firstNamereg);
            this.panel1.Controls.Add(this.repwordreg);
            this.panel1.Controls.Add(this.pwordreg);
            this.panel1.Controls.Add(this.userNamereg);
            this.panel1.Controls.Add(this.lastNamereg);
            this.panel1.Controls.Add(this.fatherNamereg);
            this.panel1.Controls.Add(this.pictureBox1);
            this.panel1.Location = new System.Drawing.Point(55, 50);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(410, 503);
            this.panel1.TabIndex = 12;
            this.panel1.Paint += new System.Windows.Forms.PaintEventHandler(this.panel1_Paint);
            // 
            // exit
            // 
            this.exit.AllowAnimations = true;
            this.exit.AllowMouseEffects = true;
            this.exit.AllowToggling = false;
            this.exit.AnimationSpeed = 200;
            this.exit.AutoGenerateColors = false;
            this.exit.AutoRoundBorders = false;
            this.exit.AutoSizeLeftIcon = true;
            this.exit.AutoSizeRightIcon = true;
            this.exit.BackColor = System.Drawing.Color.Transparent;
            this.exit.BackColor1 = System.Drawing.Color.SlateGray;
            this.exit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("exit.BackgroundImage")));
            this.exit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exit.ButtonText = "Exit";
            this.exit.ButtonTextMarginLeft = 0;
            this.exit.ColorContrastOnClick = 45;
            this.exit.ColorContrastOnHover = 45;
            this.exit.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.exit.CustomizableEdges = borderEdges1;
            this.exit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.exit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.exit.DisabledFillColor = System.Drawing.Color.Gray;
            this.exit.DisabledForecolor = System.Drawing.Color.White;
            this.exit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.exit.Font = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.exit.ForeColor = System.Drawing.Color.White;
            this.exit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.exit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.exit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.exit.IconMarginLeft = 11;
            this.exit.IconPadding = 10;
            this.exit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.exit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.exit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.exit.IconSize = 25;
            this.exit.IdleBorderColor = System.Drawing.Color.Salmon;
            this.exit.IdleBorderRadius = 1;
            this.exit.IdleBorderThickness = 1;
            this.exit.IdleFillColor = System.Drawing.Color.SlateGray;
            this.exit.IdleIconLeftImage = null;
            this.exit.IdleIconRightImage = null;
            this.exit.IndicateFocus = false;
            this.exit.Location = new System.Drawing.Point(213, 441);
            this.exit.Name = "exit";
            this.exit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.exit.OnDisabledState.BorderRadius = 1;
            this.exit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exit.OnDisabledState.BorderThickness = 1;
            this.exit.OnDisabledState.FillColor = System.Drawing.Color.Gray;
            this.exit.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.exit.OnDisabledState.IconLeftImage = null;
            this.exit.OnDisabledState.IconRightImage = null;
            this.exit.onHoverState.BorderColor = System.Drawing.Color.SlateGray;
            this.exit.onHoverState.BorderRadius = 1;
            this.exit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exit.onHoverState.BorderThickness = 1;
            this.exit.onHoverState.FillColor = System.Drawing.Color.Salmon;
            this.exit.onHoverState.ForeColor = System.Drawing.Color.Empty;
            this.exit.onHoverState.IconLeftImage = null;
            this.exit.onHoverState.IconRightImage = null;
            this.exit.OnIdleState.BorderColor = System.Drawing.Color.Salmon;
            this.exit.OnIdleState.BorderRadius = 1;
            this.exit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exit.OnIdleState.BorderThickness = 1;
            this.exit.OnIdleState.FillColor = System.Drawing.Color.SlateGray;
            this.exit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.exit.OnIdleState.IconLeftImage = null;
            this.exit.OnIdleState.IconRightImage = null;
            this.exit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.exit.OnPressedState.BorderRadius = 1;
            this.exit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exit.OnPressedState.BorderThickness = 1;
            this.exit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.exit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.exit.OnPressedState.IconLeftImage = null;
            this.exit.OnPressedState.IconRightImage = null;
            this.exit.Size = new System.Drawing.Size(118, 46);
            this.exit.TabIndex = 15;
            this.exit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.exit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.exit.TextMarginLeft = 0;
            this.exit.TextPadding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.exit.UseDefaultRadiusAndThickness = true;
            this.exit.Click += new System.EventHandler(this.exit_Click);
            // 
            // Signup
            // 
            this.Signup.AllowAnimations = true;
            this.Signup.AllowMouseEffects = true;
            this.Signup.AllowToggling = false;
            this.Signup.AnimationSpeed = 200;
            this.Signup.AutoGenerateColors = false;
            this.Signup.AutoRoundBorders = false;
            this.Signup.AutoSizeLeftIcon = true;
            this.Signup.AutoSizeRightIcon = true;
            this.Signup.BackColor = System.Drawing.Color.Transparent;
            this.Signup.BackColor1 = System.Drawing.Color.SlateGray;
            this.Signup.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Signup.BackgroundImage")));
            this.Signup.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Signup.ButtonText = "Add User";
            this.Signup.ButtonTextMarginLeft = 0;
            this.Signup.ColorContrastOnClick = 45;
            this.Signup.ColorContrastOnHover = 45;
            this.Signup.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Signup.CustomizableEdges = borderEdges2;
            this.Signup.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Signup.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.Signup.DisabledFillColor = System.Drawing.Color.Gray;
            this.Signup.DisabledForecolor = System.Drawing.Color.White;
            this.Signup.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Signup.Font = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Signup.ForeColor = System.Drawing.Color.White;
            this.Signup.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Signup.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.Signup.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Signup.IconMarginLeft = 11;
            this.Signup.IconPadding = 10;
            this.Signup.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Signup.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.Signup.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Signup.IconSize = 25;
            this.Signup.IdleBorderColor = System.Drawing.Color.Salmon;
            this.Signup.IdleBorderRadius = 1;
            this.Signup.IdleBorderThickness = 1;
            this.Signup.IdleFillColor = System.Drawing.Color.SlateGray;
            this.Signup.IdleIconLeftImage = null;
            this.Signup.IdleIconRightImage = null;
            this.Signup.IndicateFocus = false;
            this.Signup.Location = new System.Drawing.Point(79, 441);
            this.Signup.Name = "Signup";
            this.Signup.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.Signup.OnDisabledState.BorderRadius = 1;
            this.Signup.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Signup.OnDisabledState.BorderThickness = 1;
            this.Signup.OnDisabledState.FillColor = System.Drawing.Color.Gray;
            this.Signup.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.Signup.OnDisabledState.IconLeftImage = null;
            this.Signup.OnDisabledState.IconRightImage = null;
            this.Signup.onHoverState.BorderColor = System.Drawing.Color.SlateGray;
            this.Signup.onHoverState.BorderRadius = 1;
            this.Signup.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Signup.onHoverState.BorderThickness = 1;
            this.Signup.onHoverState.FillColor = System.Drawing.Color.Salmon;
            this.Signup.onHoverState.ForeColor = System.Drawing.Color.Empty;
            this.Signup.onHoverState.IconLeftImage = null;
            this.Signup.onHoverState.IconRightImage = null;
            this.Signup.OnIdleState.BorderColor = System.Drawing.Color.Salmon;
            this.Signup.OnIdleState.BorderRadius = 1;
            this.Signup.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Signup.OnIdleState.BorderThickness = 1;
            this.Signup.OnIdleState.FillColor = System.Drawing.Color.SlateGray;
            this.Signup.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Signup.OnIdleState.IconLeftImage = null;
            this.Signup.OnIdleState.IconRightImage = null;
            this.Signup.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Signup.OnPressedState.BorderRadius = 1;
            this.Signup.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Signup.OnPressedState.BorderThickness = 1;
            this.Signup.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Signup.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Signup.OnPressedState.IconLeftImage = null;
            this.Signup.OnPressedState.IconRightImage = null;
            this.Signup.Size = new System.Drawing.Size(116, 46);
            this.Signup.TabIndex = 14;
            this.Signup.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Signup.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Signup.TextMarginLeft = 0;
            this.Signup.TextPadding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.Signup.UseDefaultRadiusAndThickness = true;
            this.Signup.Click += new System.EventHandler(this.login_Click);
            // 
            // firstNamereg
            // 
            this.firstNamereg.AcceptsReturn = false;
            this.firstNamereg.AcceptsTab = false;
            this.firstNamereg.AnimationSpeed = 200;
            this.firstNamereg.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.firstNamereg.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.firstNamereg.BackColor = System.Drawing.Color.SlateGray;
            this.firstNamereg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("firstNamereg.BackgroundImage")));
            this.firstNamereg.BorderColorActive = System.Drawing.Color.Salmon;
            this.firstNamereg.BorderColorDisabled = System.Drawing.Color.SlateGray;
            this.firstNamereg.BorderColorHover = System.Drawing.Color.Salmon;
            this.firstNamereg.BorderColorIdle = System.Drawing.Color.LightSteelBlue;
            this.firstNamereg.BorderRadius = 1;
            this.firstNamereg.BorderThickness = 2;
            this.firstNamereg.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.firstNamereg.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.firstNamereg.DefaultFont = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.firstNamereg.DefaultText = "";
            this.firstNamereg.FillColor = System.Drawing.Color.SlateGray;
            this.firstNamereg.ForeColor = System.Drawing.Color.Transparent;
            this.firstNamereg.HideSelection = true;
            this.firstNamereg.IconLeft = null;
            this.firstNamereg.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.firstNamereg.IconPadding = 10;
            this.firstNamereg.IconRight = null;
            this.firstNamereg.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.firstNamereg.Lines = new string[0];
            this.firstNamereg.Location = new System.Drawing.Point(79, 159);
            this.firstNamereg.MaxLength = 32767;
            this.firstNamereg.MinimumSize = new System.Drawing.Size(100, 35);
            this.firstNamereg.Modified = false;
            this.firstNamereg.Multiline = false;
            this.firstNamereg.Name = "firstNamereg";
            stateProperties1.BorderColor = System.Drawing.Color.Salmon;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstNamereg.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.SlateGray;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.firstNamereg.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Salmon;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstNamereg.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.LightSteelBlue;
            stateProperties4.FillColor = System.Drawing.Color.SlateGray;
            stateProperties4.ForeColor = System.Drawing.Color.Transparent;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstNamereg.OnIdleState = stateProperties4;
            this.firstNamereg.PasswordChar = '\0';
            this.firstNamereg.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.firstNamereg.PlaceholderText = "First Name";
            this.firstNamereg.ReadOnly = false;
            this.firstNamereg.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.firstNamereg.SelectedText = "";
            this.firstNamereg.SelectionLength = 0;
            this.firstNamereg.SelectionStart = 0;
            this.firstNamereg.ShortcutsEnabled = true;
            this.firstNamereg.Size = new System.Drawing.Size(252, 37);
            this.firstNamereg.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.firstNamereg.TabIndex = 11;
            this.firstNamereg.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.firstNamereg.TextMarginBottom = 0;
            this.firstNamereg.TextMarginLeft = 5;
            this.firstNamereg.TextMarginTop = 0;
            this.firstNamereg.TextPlaceholder = "First Name";
            this.firstNamereg.UseSystemPasswordChar = false;
            this.firstNamereg.WordWrap = true;
            this.firstNamereg.TextChange += new System.EventHandler(this.firstNamereg_TextChange);
            // 
            // repwordreg
            // 
            this.repwordreg.AcceptsReturn = false;
            this.repwordreg.AcceptsTab = false;
            this.repwordreg.AnimationSpeed = 200;
            this.repwordreg.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.repwordreg.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.repwordreg.BackColor = System.Drawing.Color.SlateGray;
            this.repwordreg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("repwordreg.BackgroundImage")));
            this.repwordreg.BorderColorActive = System.Drawing.Color.Salmon;
            this.repwordreg.BorderColorDisabled = System.Drawing.Color.SlateGray;
            this.repwordreg.BorderColorHover = System.Drawing.Color.Salmon;
            this.repwordreg.BorderColorIdle = System.Drawing.Color.LightSteelBlue;
            this.repwordreg.BorderRadius = 1;
            this.repwordreg.BorderThickness = 2;
            this.repwordreg.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.repwordreg.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.repwordreg.DefaultFont = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.repwordreg.DefaultText = "";
            this.repwordreg.FillColor = System.Drawing.Color.SlateGray;
            this.repwordreg.ForeColor = System.Drawing.Color.Transparent;
            this.repwordreg.HideSelection = true;
            this.repwordreg.IconLeft = null;
            this.repwordreg.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.repwordreg.IconPadding = 10;
            this.repwordreg.IconRight = null;
            this.repwordreg.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.repwordreg.Lines = new string[0];
            this.repwordreg.Location = new System.Drawing.Point(79, 374);
            this.repwordreg.MaxLength = 32767;
            this.repwordreg.MinimumSize = new System.Drawing.Size(100, 35);
            this.repwordreg.Modified = false;
            this.repwordreg.Multiline = false;
            this.repwordreg.Name = "repwordreg";
            stateProperties5.BorderColor = System.Drawing.Color.Salmon;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.repwordreg.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.SlateGray;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.repwordreg.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Salmon;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.repwordreg.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.LightSteelBlue;
            stateProperties8.FillColor = System.Drawing.Color.SlateGray;
            stateProperties8.ForeColor = System.Drawing.Color.Transparent;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.repwordreg.OnIdleState = stateProperties8;
            this.repwordreg.PasswordChar = '*';
            this.repwordreg.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.repwordreg.PlaceholderText = "Retype Password";
            this.repwordreg.ReadOnly = false;
            this.repwordreg.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.repwordreg.SelectedText = "";
            this.repwordreg.SelectionLength = 0;
            this.repwordreg.SelectionStart = 0;
            this.repwordreg.ShortcutsEnabled = true;
            this.repwordreg.Size = new System.Drawing.Size(252, 37);
            this.repwordreg.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.repwordreg.TabIndex = 11;
            this.repwordreg.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.repwordreg.TextMarginBottom = 0;
            this.repwordreg.TextMarginLeft = 5;
            this.repwordreg.TextMarginTop = 0;
            this.repwordreg.TextPlaceholder = "Retype Password";
            this.repwordreg.UseSystemPasswordChar = false;
            this.repwordreg.WordWrap = true;
            this.repwordreg.TextChange += new System.EventHandler(this.repwordreg_TextChange);
            // 
            // pwordreg
            // 
            this.pwordreg.AcceptsReturn = false;
            this.pwordreg.AcceptsTab = false;
            this.pwordreg.AnimationSpeed = 200;
            this.pwordreg.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.pwordreg.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.pwordreg.BackColor = System.Drawing.Color.SlateGray;
            this.pwordreg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pwordreg.BackgroundImage")));
            this.pwordreg.BorderColorActive = System.Drawing.Color.Salmon;
            this.pwordreg.BorderColorDisabled = System.Drawing.Color.SlateGray;
            this.pwordreg.BorderColorHover = System.Drawing.Color.Salmon;
            this.pwordreg.BorderColorIdle = System.Drawing.Color.LightSteelBlue;
            this.pwordreg.BorderRadius = 1;
            this.pwordreg.BorderThickness = 2;
            this.pwordreg.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.pwordreg.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.pwordreg.DefaultFont = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.pwordreg.DefaultText = "";
            this.pwordreg.FillColor = System.Drawing.Color.SlateGray;
            this.pwordreg.ForeColor = System.Drawing.Color.Transparent;
            this.pwordreg.HideSelection = true;
            this.pwordreg.IconLeft = null;
            this.pwordreg.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.pwordreg.IconPadding = 10;
            this.pwordreg.IconRight = null;
            this.pwordreg.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.pwordreg.Lines = new string[0];
            this.pwordreg.Location = new System.Drawing.Point(79, 331);
            this.pwordreg.MaxLength = 32767;
            this.pwordreg.MinimumSize = new System.Drawing.Size(100, 35);
            this.pwordreg.Modified = false;
            this.pwordreg.Multiline = false;
            this.pwordreg.Name = "pwordreg";
            stateProperties9.BorderColor = System.Drawing.Color.Salmon;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.pwordreg.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.SlateGray;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.pwordreg.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Salmon;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.pwordreg.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.LightSteelBlue;
            stateProperties12.FillColor = System.Drawing.Color.SlateGray;
            stateProperties12.ForeColor = System.Drawing.Color.Transparent;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.pwordreg.OnIdleState = stateProperties12;
            this.pwordreg.PasswordChar = '*';
            this.pwordreg.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.pwordreg.PlaceholderText = "Password";
            this.pwordreg.ReadOnly = false;
            this.pwordreg.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.pwordreg.SelectedText = "";
            this.pwordreg.SelectionLength = 0;
            this.pwordreg.SelectionStart = 0;
            this.pwordreg.ShortcutsEnabled = true;
            this.pwordreg.Size = new System.Drawing.Size(252, 37);
            this.pwordreg.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.pwordreg.TabIndex = 11;
            this.pwordreg.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.pwordreg.TextMarginBottom = 0;
            this.pwordreg.TextMarginLeft = 5;
            this.pwordreg.TextMarginTop = 0;
            this.pwordreg.TextPlaceholder = "Password";
            this.pwordreg.UseSystemPasswordChar = false;
            this.pwordreg.WordWrap = true;
            this.pwordreg.TextChange += new System.EventHandler(this.pwordreg_TextChange);
            // 
            // userNamereg
            // 
            this.userNamereg.AcceptsReturn = false;
            this.userNamereg.AcceptsTab = false;
            this.userNamereg.AnimationSpeed = 200;
            this.userNamereg.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.userNamereg.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.userNamereg.BackColor = System.Drawing.Color.SlateGray;
            this.userNamereg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("userNamereg.BackgroundImage")));
            this.userNamereg.BorderColorActive = System.Drawing.Color.Salmon;
            this.userNamereg.BorderColorDisabled = System.Drawing.Color.SlateGray;
            this.userNamereg.BorderColorHover = System.Drawing.Color.Salmon;
            this.userNamereg.BorderColorIdle = System.Drawing.Color.LightSteelBlue;
            this.userNamereg.BorderRadius = 1;
            this.userNamereg.BorderThickness = 2;
            this.userNamereg.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.userNamereg.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.userNamereg.DefaultFont = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.userNamereg.DefaultText = "";
            this.userNamereg.FillColor = System.Drawing.Color.SlateGray;
            this.userNamereg.ForeColor = System.Drawing.Color.Transparent;
            this.userNamereg.HideSelection = true;
            this.userNamereg.IconLeft = null;
            this.userNamereg.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.userNamereg.IconPadding = 10;
            this.userNamereg.IconRight = null;
            this.userNamereg.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.userNamereg.Lines = new string[0];
            this.userNamereg.Location = new System.Drawing.Point(79, 288);
            this.userNamereg.MaxLength = 32767;
            this.userNamereg.MinimumSize = new System.Drawing.Size(100, 35);
            this.userNamereg.Modified = false;
            this.userNamereg.Multiline = false;
            this.userNamereg.Name = "userNamereg";
            stateProperties13.BorderColor = System.Drawing.Color.Salmon;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.userNamereg.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.SlateGray;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.userNamereg.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Salmon;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.userNamereg.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.LightSteelBlue;
            stateProperties16.FillColor = System.Drawing.Color.SlateGray;
            stateProperties16.ForeColor = System.Drawing.Color.Transparent;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.userNamereg.OnIdleState = stateProperties16;
            this.userNamereg.PasswordChar = '\0';
            this.userNamereg.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.userNamereg.PlaceholderText = "Username";
            this.userNamereg.ReadOnly = false;
            this.userNamereg.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.userNamereg.SelectedText = "";
            this.userNamereg.SelectionLength = 0;
            this.userNamereg.SelectionStart = 0;
            this.userNamereg.ShortcutsEnabled = true;
            this.userNamereg.Size = new System.Drawing.Size(252, 37);
            this.userNamereg.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.userNamereg.TabIndex = 11;
            this.userNamereg.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.userNamereg.TextMarginBottom = 0;
            this.userNamereg.TextMarginLeft = 5;
            this.userNamereg.TextMarginTop = 0;
            this.userNamereg.TextPlaceholder = "Username";
            this.userNamereg.UseSystemPasswordChar = false;
            this.userNamereg.WordWrap = true;
            this.userNamereg.TextChange += new System.EventHandler(this.userNamereg_TextChange);
            // 
            // lastNamereg
            // 
            this.lastNamereg.AcceptsReturn = false;
            this.lastNamereg.AcceptsTab = false;
            this.lastNamereg.AnimationSpeed = 200;
            this.lastNamereg.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.lastNamereg.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.lastNamereg.BackColor = System.Drawing.Color.SlateGray;
            this.lastNamereg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("lastNamereg.BackgroundImage")));
            this.lastNamereg.BorderColorActive = System.Drawing.Color.Salmon;
            this.lastNamereg.BorderColorDisabled = System.Drawing.Color.SlateGray;
            this.lastNamereg.BorderColorHover = System.Drawing.Color.Salmon;
            this.lastNamereg.BorderColorIdle = System.Drawing.Color.LightSteelBlue;
            this.lastNamereg.BorderRadius = 1;
            this.lastNamereg.BorderThickness = 2;
            this.lastNamereg.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.lastNamereg.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.lastNamereg.DefaultFont = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lastNamereg.DefaultText = "";
            this.lastNamereg.FillColor = System.Drawing.Color.SlateGray;
            this.lastNamereg.ForeColor = System.Drawing.Color.Transparent;
            this.lastNamereg.HideSelection = true;
            this.lastNamereg.IconLeft = null;
            this.lastNamereg.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.lastNamereg.IconPadding = 10;
            this.lastNamereg.IconRight = null;
            this.lastNamereg.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.lastNamereg.Lines = new string[0];
            this.lastNamereg.Location = new System.Drawing.Point(79, 202);
            this.lastNamereg.MaxLength = 32767;
            this.lastNamereg.MinimumSize = new System.Drawing.Size(100, 35);
            this.lastNamereg.Modified = false;
            this.lastNamereg.Multiline = false;
            this.lastNamereg.Name = "lastNamereg";
            stateProperties17.BorderColor = System.Drawing.Color.Salmon;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNamereg.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.SlateGray;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.lastNamereg.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.Salmon;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNamereg.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.LightSteelBlue;
            stateProperties20.FillColor = System.Drawing.Color.SlateGray;
            stateProperties20.ForeColor = System.Drawing.Color.Transparent;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNamereg.OnIdleState = stateProperties20;
            this.lastNamereg.PasswordChar = '\0';
            this.lastNamereg.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.lastNamereg.PlaceholderText = "Last Name";
            this.lastNamereg.ReadOnly = false;
            this.lastNamereg.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.lastNamereg.SelectedText = "";
            this.lastNamereg.SelectionLength = 0;
            this.lastNamereg.SelectionStart = 0;
            this.lastNamereg.ShortcutsEnabled = true;
            this.lastNamereg.Size = new System.Drawing.Size(252, 37);
            this.lastNamereg.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.lastNamereg.TabIndex = 11;
            this.lastNamereg.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.lastNamereg.TextMarginBottom = 0;
            this.lastNamereg.TextMarginLeft = 5;
            this.lastNamereg.TextMarginTop = 0;
            this.lastNamereg.TextPlaceholder = "Last Name";
            this.lastNamereg.UseSystemPasswordChar = false;
            this.lastNamereg.WordWrap = true;
            this.lastNamereg.TextChange += new System.EventHandler(this.lastNamereg_TextChange);
            // 
            // fatherNamereg
            // 
            this.fatherNamereg.AcceptsReturn = false;
            this.fatherNamereg.AcceptsTab = false;
            this.fatherNamereg.AnimationSpeed = 200;
            this.fatherNamereg.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.fatherNamereg.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.fatherNamereg.BackColor = System.Drawing.Color.SlateGray;
            this.fatherNamereg.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("fatherNamereg.BackgroundImage")));
            this.fatherNamereg.BorderColorActive = System.Drawing.Color.Salmon;
            this.fatherNamereg.BorderColorDisabled = System.Drawing.Color.SlateGray;
            this.fatherNamereg.BorderColorHover = System.Drawing.Color.Salmon;
            this.fatherNamereg.BorderColorIdle = System.Drawing.Color.LightSteelBlue;
            this.fatherNamereg.BorderRadius = 1;
            this.fatherNamereg.BorderThickness = 2;
            this.fatherNamereg.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.fatherNamereg.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.fatherNamereg.DefaultFont = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.fatherNamereg.DefaultText = "";
            this.fatherNamereg.FillColor = System.Drawing.Color.SlateGray;
            this.fatherNamereg.ForeColor = System.Drawing.Color.Transparent;
            this.fatherNamereg.HideSelection = true;
            this.fatherNamereg.IconLeft = null;
            this.fatherNamereg.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.fatherNamereg.IconPadding = 10;
            this.fatherNamereg.IconRight = null;
            this.fatherNamereg.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.fatherNamereg.Lines = new string[0];
            this.fatherNamereg.Location = new System.Drawing.Point(79, 245);
            this.fatherNamereg.MaxLength = 32767;
            this.fatherNamereg.MinimumSize = new System.Drawing.Size(100, 35);
            this.fatherNamereg.Modified = false;
            this.fatherNamereg.Multiline = false;
            this.fatherNamereg.Name = "fatherNamereg";
            stateProperties21.BorderColor = System.Drawing.Color.Salmon;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.fatherNamereg.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.SlateGray;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.Empty;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.fatherNamereg.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.Salmon;
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.fatherNamereg.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.LightSteelBlue;
            stateProperties24.FillColor = System.Drawing.Color.SlateGray;
            stateProperties24.ForeColor = System.Drawing.Color.Transparent;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.fatherNamereg.OnIdleState = stateProperties24;
            this.fatherNamereg.PasswordChar = '\0';
            this.fatherNamereg.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.fatherNamereg.PlaceholderText = "Father\'s Name";
            this.fatherNamereg.ReadOnly = false;
            this.fatherNamereg.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.fatherNamereg.SelectedText = "";
            this.fatherNamereg.SelectionLength = 0;
            this.fatherNamereg.SelectionStart = 0;
            this.fatherNamereg.ShortcutsEnabled = true;
            this.fatherNamereg.Size = new System.Drawing.Size(252, 37);
            this.fatherNamereg.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.fatherNamereg.TabIndex = 11;
            this.fatherNamereg.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.fatherNamereg.TextMarginBottom = 0;
            this.fatherNamereg.TextMarginLeft = 5;
            this.fatherNamereg.TextMarginTop = 0;
            this.fatherNamereg.TextPlaceholder = "Father\'s Name";
            this.fatherNamereg.UseSystemPasswordChar = false;
            this.fatherNamereg.WordWrap = true;
            this.fatherNamereg.TextChange += new System.EventHandler(this.fatherNamereg_TextChange);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(137, 3);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(134, 136);
            this.pictureBox1.TabIndex = 13;
            this.pictureBox1.TabStop = false;
            this.pictureBox1.Click += new System.EventHandler(this.pictureBox1_Click);
            // 
            // Register
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(521, 579);
            this.Controls.Add(this.registerUser);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Register";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Register";
            this.registerUser.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.MinBtn)).EndInit();
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel registerUser;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox firstNamereg;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox repwordreg;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox pwordreg;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox userNamereg;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox lastNamereg;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox fatherNamereg;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Signup;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton exit;
        private System.Windows.Forms.PictureBox MinBtn;
    }
}