namespace Pro
{
    partial class Student_Form
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Student_Form));
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            this.registerUser = new System.Windows.Forms.Panel();
            this.panel1 = new System.Windows.Forms.Panel();
            this.stdListFormLbl = new System.Windows.Forms.Label();
            this.semesterBox = new System.Windows.Forms.ComboBox();
            this.courseText = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.courseBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.courseBox = new System.Windows.Forms.ComboBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.femaleRadioBtn = new System.Windows.Forms.RadioButton();
            this.maleRadioBtn = new System.Windows.Forms.RadioButton();
            this.exit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.addStudent = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.firstNameStd = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.addressStd = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.contactStd = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.ageStd = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.lastNameStd = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.fatherNameStd = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.registerUser.SuspendLayout();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // registerUser
            // 
            this.registerUser.BackColor = System.Drawing.Color.Salmon;
            this.registerUser.Controls.Add(this.panel1);
            this.registerUser.Location = new System.Drawing.Point(-1, 0);
            this.registerUser.Name = "registerUser";
            this.registerUser.Size = new System.Drawing.Size(698, 708);
            this.registerUser.TabIndex = 2;
            this.registerUser.Paint += new System.Windows.Forms.PaintEventHandler(this.registerUser_Paint);
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.SlateGray;
            this.panel1.Controls.Add(this.stdListFormLbl);
            this.panel1.Controls.Add(this.semesterBox);
            this.panel1.Controls.Add(this.courseText);
            this.panel1.Controls.Add(this.courseBtn);
            this.panel1.Controls.Add(this.courseBox);
            this.panel1.Controls.Add(this.pictureBox1);
            this.panel1.Controls.Add(this.femaleRadioBtn);
            this.panel1.Controls.Add(this.maleRadioBtn);
            this.panel1.Controls.Add(this.exit);
            this.panel1.Controls.Add(this.addStudent);
            this.panel1.Controls.Add(this.firstNameStd);
            this.panel1.Controls.Add(this.addressStd);
            this.panel1.Controls.Add(this.contactStd);
            this.panel1.Controls.Add(this.ageStd);
            this.panel1.Controls.Add(this.lastNameStd);
            this.panel1.Controls.Add(this.fatherNameStd);
            this.panel1.Location = new System.Drawing.Point(58, 41);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(590, 607);
            this.panel1.TabIndex = 12;
            this.panel1.Paint += new System.Windows.Forms.PaintEventHandler(this.panel1_Paint);
            // 
            // stdListFormLbl
            // 
            this.stdListFormLbl.AutoSize = true;
            this.stdListFormLbl.BackColor = System.Drawing.Color.Salmon;
            this.stdListFormLbl.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.stdListFormLbl.Font = new System.Drawing.Font("Palatino Linotype", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.stdListFormLbl.ForeColor = System.Drawing.Color.Transparent;
            this.stdListFormLbl.Location = new System.Drawing.Point(372, 389);
            this.stdListFormLbl.Name = "stdListFormLbl";
            this.stdListFormLbl.Size = new System.Drawing.Size(103, 30);
            this.stdListFormLbl.TabIndex = 28;
            this.stdListFormLbl.Text = "Semester";
            // 
            // semesterBox
            // 
            this.semesterBox.BackColor = System.Drawing.Color.SlateGray;
            this.semesterBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.semesterBox.Font = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.semesterBox.ForeColor = System.Drawing.Color.White;
            this.semesterBox.FormattingEnabled = true;
            this.semesterBox.Location = new System.Drawing.Point(312, 430);
            this.semesterBox.Name = "semesterBox";
            this.semesterBox.Size = new System.Drawing.Size(252, 30);
            this.semesterBox.TabIndex = 25;
            this.semesterBox.SelectedIndexChanged += new System.EventHandler(this.semesterBox_SelectedIndexChanged);
            // 
            // courseText
            // 
            this.courseText.AcceptsReturn = false;
            this.courseText.AcceptsTab = false;
            this.courseText.AnimationSpeed = 200;
            this.courseText.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.courseText.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.courseText.BackColor = System.Drawing.Color.SlateGray;
            this.courseText.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("courseText.BackgroundImage")));
            this.courseText.BorderColorActive = System.Drawing.Color.Salmon;
            this.courseText.BorderColorDisabled = System.Drawing.Color.SlateGray;
            this.courseText.BorderColorHover = System.Drawing.Color.Salmon;
            this.courseText.BorderColorIdle = System.Drawing.Color.LightSteelBlue;
            this.courseText.BorderRadius = 1;
            this.courseText.BorderThickness = 2;
            this.courseText.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.courseText.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.courseText.DefaultFont = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.courseText.DefaultText = "";
            this.courseText.FillColor = System.Drawing.Color.SlateGray;
            this.courseText.ForeColor = System.Drawing.Color.Transparent;
            this.courseText.HideSelection = true;
            this.courseText.IconLeft = null;
            this.courseText.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.courseText.IconPadding = 10;
            this.courseText.IconRight = null;
            this.courseText.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.courseText.Lines = new string[0];
            this.courseText.Location = new System.Drawing.Point(29, 389);
            this.courseText.MaxLength = 32767;
            this.courseText.MinimumSize = new System.Drawing.Size(100, 35);
            this.courseText.Modified = false;
            this.courseText.Multiline = false;
            this.courseText.Name = "courseText";
            stateProperties1.BorderColor = System.Drawing.Color.Salmon;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.courseText.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.SlateGray;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.courseText.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Salmon;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.courseText.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.LightSteelBlue;
            stateProperties4.FillColor = System.Drawing.Color.SlateGray;
            stateProperties4.ForeColor = System.Drawing.Color.Transparent;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.courseText.OnIdleState = stateProperties4;
            this.courseText.PasswordChar = '\0';
            this.courseText.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.courseText.PlaceholderText = "New Course";
            this.courseText.ReadOnly = false;
            this.courseText.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.courseText.SelectedText = "";
            this.courseText.SelectionLength = 0;
            this.courseText.SelectionStart = 0;
            this.courseText.ShortcutsEnabled = true;
            this.courseText.Size = new System.Drawing.Size(147, 35);
            this.courseText.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.courseText.TabIndex = 24;
            this.courseText.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.courseText.TextMarginBottom = 0;
            this.courseText.TextMarginLeft = 5;
            this.courseText.TextMarginTop = 0;
            this.courseText.TextPlaceholder = "New Course";
            this.courseText.UseSystemPasswordChar = false;
            this.courseText.WordWrap = true;
            this.courseText.TextChange += new System.EventHandler(this.courseText_TextChange);
            // 
            // courseBtn
            // 
            this.courseBtn.AllowAnimations = true;
            this.courseBtn.AllowMouseEffects = true;
            this.courseBtn.AllowToggling = false;
            this.courseBtn.AnimationSpeed = 200;
            this.courseBtn.AutoGenerateColors = false;
            this.courseBtn.AutoRoundBorders = false;
            this.courseBtn.AutoSizeLeftIcon = true;
            this.courseBtn.AutoSizeRightIcon = true;
            this.courseBtn.BackColor = System.Drawing.Color.Transparent;
            this.courseBtn.BackColor1 = System.Drawing.Color.SlateGray;
            this.courseBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("courseBtn.BackgroundImage")));
            this.courseBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.courseBtn.ButtonText = "Add Course";
            this.courseBtn.ButtonTextMarginLeft = 0;
            this.courseBtn.ColorContrastOnClick = 45;
            this.courseBtn.ColorContrastOnHover = 45;
            this.courseBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.courseBtn.CustomizableEdges = borderEdges1;
            this.courseBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.courseBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.courseBtn.DisabledFillColor = System.Drawing.Color.Gray;
            this.courseBtn.DisabledForecolor = System.Drawing.Color.White;
            this.courseBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.courseBtn.Font = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.courseBtn.ForeColor = System.Drawing.Color.White;
            this.courseBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.courseBtn.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.courseBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.courseBtn.IconMarginLeft = 11;
            this.courseBtn.IconPadding = 10;
            this.courseBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.courseBtn.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.courseBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.courseBtn.IconSize = 25;
            this.courseBtn.IdleBorderColor = System.Drawing.Color.Salmon;
            this.courseBtn.IdleBorderRadius = 1;
            this.courseBtn.IdleBorderThickness = 1;
            this.courseBtn.IdleFillColor = System.Drawing.Color.SlateGray;
            this.courseBtn.IdleIconLeftImage = null;
            this.courseBtn.IdleIconRightImage = null;
            this.courseBtn.IndicateFocus = false;
            this.courseBtn.Location = new System.Drawing.Point(182, 389);
            this.courseBtn.Name = "courseBtn";
            this.courseBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.courseBtn.OnDisabledState.BorderRadius = 1;
            this.courseBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.courseBtn.OnDisabledState.BorderThickness = 1;
            this.courseBtn.OnDisabledState.FillColor = System.Drawing.Color.Gray;
            this.courseBtn.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.courseBtn.OnDisabledState.IconLeftImage = null;
            this.courseBtn.OnDisabledState.IconRightImage = null;
            this.courseBtn.onHoverState.BorderColor = System.Drawing.Color.SlateGray;
            this.courseBtn.onHoverState.BorderRadius = 1;
            this.courseBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.courseBtn.onHoverState.BorderThickness = 1;
            this.courseBtn.onHoverState.FillColor = System.Drawing.Color.Salmon;
            this.courseBtn.onHoverState.ForeColor = System.Drawing.Color.Empty;
            this.courseBtn.onHoverState.IconLeftImage = null;
            this.courseBtn.onHoverState.IconRightImage = null;
            this.courseBtn.OnIdleState.BorderColor = System.Drawing.Color.Salmon;
            this.courseBtn.OnIdleState.BorderRadius = 1;
            this.courseBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.courseBtn.OnIdleState.BorderThickness = 1;
            this.courseBtn.OnIdleState.FillColor = System.Drawing.Color.SlateGray;
            this.courseBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.courseBtn.OnIdleState.IconLeftImage = null;
            this.courseBtn.OnIdleState.IconRightImage = null;
            this.courseBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.courseBtn.OnPressedState.BorderRadius = 1;
            this.courseBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.courseBtn.OnPressedState.BorderThickness = 1;
            this.courseBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.courseBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.courseBtn.OnPressedState.IconLeftImage = null;
            this.courseBtn.OnPressedState.IconRightImage = null;
            this.courseBtn.Size = new System.Drawing.Size(99, 34);
            this.courseBtn.TabIndex = 23;
            this.courseBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.courseBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.courseBtn.TextMarginLeft = 0;
            this.courseBtn.TextPadding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.courseBtn.UseDefaultRadiusAndThickness = true;
            this.courseBtn.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // courseBox
            // 
            this.courseBox.BackColor = System.Drawing.Color.SlateGray;
            this.courseBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.courseBox.Font = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.courseBox.FormattingEnabled = true;
            this.courseBox.Location = new System.Drawing.Point(29, 430);
            this.courseBox.Name = "courseBox";
            this.courseBox.Size = new System.Drawing.Size(252, 30);
            this.courseBox.TabIndex = 22;
            this.courseBox.SelectedIndexChanged += new System.EventHandler(this.courseBox_SelectedIndexChanged);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::Pro.Properties.Resources.std;
            this.pictureBox1.Location = new System.Drawing.Point(232, 12);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(128, 138);
            this.pictureBox1.TabIndex = 21;
            this.pictureBox1.TabStop = false;
            // 
            // femaleRadioBtn
            // 
            this.femaleRadioBtn.AutoSize = true;
            this.femaleRadioBtn.FlatAppearance.BorderColor = System.Drawing.Color.LightSlateGray;
            this.femaleRadioBtn.FlatAppearance.CheckedBackColor = System.Drawing.Color.LightSlateGray;
            this.femaleRadioBtn.Font = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.femaleRadioBtn.ForeColor = System.Drawing.Color.Silver;
            this.femaleRadioBtn.Location = new System.Drawing.Point(315, 343);
            this.femaleRadioBtn.Name = "femaleRadioBtn";
            this.femaleRadioBtn.Size = new System.Drawing.Size(77, 26);
            this.femaleRadioBtn.TabIndex = 20;
            this.femaleRadioBtn.TabStop = true;
            this.femaleRadioBtn.Text = "Female";
            this.femaleRadioBtn.UseVisualStyleBackColor = true;
            this.femaleRadioBtn.CheckedChanged += new System.EventHandler(this.femaleRadioBtn_CheckedChanged);
            // 
            // maleRadioBtn
            // 
            this.maleRadioBtn.AutoSize = true;
            this.maleRadioBtn.FlatAppearance.BorderColor = System.Drawing.Color.LightSlateGray;
            this.maleRadioBtn.FlatAppearance.CheckedBackColor = System.Drawing.Color.LightSlateGray;
            this.maleRadioBtn.Font = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.maleRadioBtn.ForeColor = System.Drawing.Color.Silver;
            this.maleRadioBtn.Location = new System.Drawing.Point(244, 343);
            this.maleRadioBtn.Name = "maleRadioBtn";
            this.maleRadioBtn.Size = new System.Drawing.Size(62, 26);
            this.maleRadioBtn.TabIndex = 19;
            this.maleRadioBtn.TabStop = true;
            this.maleRadioBtn.Text = "Male";
            this.maleRadioBtn.UseVisualStyleBackColor = true;
            this.maleRadioBtn.CheckedChanged += new System.EventHandler(this.maleRadioBtn_CheckedChanged);
            // 
            // exit
            // 
            this.exit.AllowAnimations = true;
            this.exit.AllowMouseEffects = true;
            this.exit.AllowToggling = false;
            this.exit.AnimationSpeed = 200;
            this.exit.AutoGenerateColors = false;
            this.exit.AutoRoundBorders = false;
            this.exit.AutoSizeLeftIcon = true;
            this.exit.AutoSizeRightIcon = true;
            this.exit.BackColor = System.Drawing.Color.Transparent;
            this.exit.BackColor1 = System.Drawing.Color.SlateGray;
            this.exit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("exit.BackgroundImage")));
            this.exit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exit.ButtonText = "Exit";
            this.exit.ButtonTextMarginLeft = 0;
            this.exit.ColorContrastOnClick = 45;
            this.exit.ColorContrastOnHover = 45;
            this.exit.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.exit.CustomizableEdges = borderEdges2;
            this.exit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.exit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.exit.DisabledFillColor = System.Drawing.Color.Gray;
            this.exit.DisabledForecolor = System.Drawing.Color.White;
            this.exit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.exit.Font = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.exit.ForeColor = System.Drawing.Color.White;
            this.exit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.exit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.exit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.exit.IconMarginLeft = 11;
            this.exit.IconPadding = 10;
            this.exit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.exit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.exit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.exit.IconSize = 25;
            this.exit.IdleBorderColor = System.Drawing.Color.Salmon;
            this.exit.IdleBorderRadius = 1;
            this.exit.IdleBorderThickness = 1;
            this.exit.IdleFillColor = System.Drawing.Color.SlateGray;
            this.exit.IdleIconLeftImage = null;
            this.exit.IdleIconRightImage = null;
            this.exit.IndicateFocus = false;
            this.exit.Location = new System.Drawing.Point(312, 525);
            this.exit.Name = "exit";
            this.exit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.exit.OnDisabledState.BorderRadius = 1;
            this.exit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exit.OnDisabledState.BorderThickness = 1;
            this.exit.OnDisabledState.FillColor = System.Drawing.Color.Gray;
            this.exit.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.exit.OnDisabledState.IconLeftImage = null;
            this.exit.OnDisabledState.IconRightImage = null;
            this.exit.onHoverState.BorderColor = System.Drawing.Color.SlateGray;
            this.exit.onHoverState.BorderRadius = 1;
            this.exit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exit.onHoverState.BorderThickness = 1;
            this.exit.onHoverState.FillColor = System.Drawing.Color.Salmon;
            this.exit.onHoverState.ForeColor = System.Drawing.Color.Empty;
            this.exit.onHoverState.IconLeftImage = null;
            this.exit.onHoverState.IconRightImage = null;
            this.exit.OnIdleState.BorderColor = System.Drawing.Color.Salmon;
            this.exit.OnIdleState.BorderRadius = 1;
            this.exit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exit.OnIdleState.BorderThickness = 1;
            this.exit.OnIdleState.FillColor = System.Drawing.Color.SlateGray;
            this.exit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.exit.OnIdleState.IconLeftImage = null;
            this.exit.OnIdleState.IconRightImage = null;
            this.exit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.exit.OnPressedState.BorderRadius = 1;
            this.exit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exit.OnPressedState.BorderThickness = 1;
            this.exit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.exit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.exit.OnPressedState.IconLeftImage = null;
            this.exit.OnPressedState.IconRightImage = null;
            this.exit.Size = new System.Drawing.Size(252, 46);
            this.exit.TabIndex = 15;
            this.exit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.exit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.exit.TextMarginLeft = 0;
            this.exit.TextPadding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.exit.UseDefaultRadiusAndThickness = true;
            this.exit.Click += new System.EventHandler(this.exit_Click);
            // 
            // addStudent
            // 
            this.addStudent.AllowAnimations = true;
            this.addStudent.AllowMouseEffects = true;
            this.addStudent.AllowToggling = false;
            this.addStudent.AnimationSpeed = 200;
            this.addStudent.AutoGenerateColors = false;
            this.addStudent.AutoRoundBorders = false;
            this.addStudent.AutoSizeLeftIcon = true;
            this.addStudent.AutoSizeRightIcon = true;
            this.addStudent.BackColor = System.Drawing.Color.Transparent;
            this.addStudent.BackColor1 = System.Drawing.Color.SlateGray;
            this.addStudent.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addStudent.BackgroundImage")));
            this.addStudent.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addStudent.ButtonText = "Add Student";
            this.addStudent.ButtonTextMarginLeft = 0;
            this.addStudent.ColorContrastOnClick = 45;
            this.addStudent.ColorContrastOnHover = 45;
            this.addStudent.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.addStudent.CustomizableEdges = borderEdges3;
            this.addStudent.DialogResult = System.Windows.Forms.DialogResult.None;
            this.addStudent.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.addStudent.DisabledFillColor = System.Drawing.Color.Gray;
            this.addStudent.DisabledForecolor = System.Drawing.Color.White;
            this.addStudent.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.addStudent.Font = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addStudent.ForeColor = System.Drawing.Color.White;
            this.addStudent.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addStudent.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.addStudent.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.addStudent.IconMarginLeft = 11;
            this.addStudent.IconPadding = 10;
            this.addStudent.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.addStudent.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.addStudent.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.addStudent.IconSize = 25;
            this.addStudent.IdleBorderColor = System.Drawing.Color.Salmon;
            this.addStudent.IdleBorderRadius = 1;
            this.addStudent.IdleBorderThickness = 1;
            this.addStudent.IdleFillColor = System.Drawing.Color.SlateGray;
            this.addStudent.IdleIconLeftImage = null;
            this.addStudent.IdleIconRightImage = null;
            this.addStudent.IndicateFocus = false;
            this.addStudent.Location = new System.Drawing.Point(29, 525);
            this.addStudent.Name = "addStudent";
            this.addStudent.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.addStudent.OnDisabledState.BorderRadius = 1;
            this.addStudent.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addStudent.OnDisabledState.BorderThickness = 1;
            this.addStudent.OnDisabledState.FillColor = System.Drawing.Color.Gray;
            this.addStudent.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.addStudent.OnDisabledState.IconLeftImage = null;
            this.addStudent.OnDisabledState.IconRightImage = null;
            this.addStudent.onHoverState.BorderColor = System.Drawing.Color.SlateGray;
            this.addStudent.onHoverState.BorderRadius = 1;
            this.addStudent.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addStudent.onHoverState.BorderThickness = 1;
            this.addStudent.onHoverState.FillColor = System.Drawing.Color.Salmon;
            this.addStudent.onHoverState.ForeColor = System.Drawing.Color.Empty;
            this.addStudent.onHoverState.IconLeftImage = null;
            this.addStudent.onHoverState.IconRightImage = null;
            this.addStudent.OnIdleState.BorderColor = System.Drawing.Color.Salmon;
            this.addStudent.OnIdleState.BorderRadius = 1;
            this.addStudent.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addStudent.OnIdleState.BorderThickness = 1;
            this.addStudent.OnIdleState.FillColor = System.Drawing.Color.SlateGray;
            this.addStudent.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.addStudent.OnIdleState.IconLeftImage = null;
            this.addStudent.OnIdleState.IconRightImage = null;
            this.addStudent.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addStudent.OnPressedState.BorderRadius = 1;
            this.addStudent.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addStudent.OnPressedState.BorderThickness = 1;
            this.addStudent.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addStudent.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.addStudent.OnPressedState.IconLeftImage = null;
            this.addStudent.OnPressedState.IconRightImage = null;
            this.addStudent.Size = new System.Drawing.Size(252, 46);
            this.addStudent.TabIndex = 14;
            this.addStudent.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.addStudent.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.addStudent.TextMarginLeft = 0;
            this.addStudent.TextPadding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            this.addStudent.UseDefaultRadiusAndThickness = true;
            this.addStudent.Click += new System.EventHandler(this.Signup_Click);
            // 
            // firstNameStd
            // 
            this.firstNameStd.AcceptsReturn = false;
            this.firstNameStd.AcceptsTab = false;
            this.firstNameStd.AnimationSpeed = 200;
            this.firstNameStd.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.firstNameStd.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.firstNameStd.BackColor = System.Drawing.Color.SlateGray;
            this.firstNameStd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("firstNameStd.BackgroundImage")));
            this.firstNameStd.BorderColorActive = System.Drawing.Color.Salmon;
            this.firstNameStd.BorderColorDisabled = System.Drawing.Color.SlateGray;
            this.firstNameStd.BorderColorHover = System.Drawing.Color.Salmon;
            this.firstNameStd.BorderColorIdle = System.Drawing.Color.LightSteelBlue;
            this.firstNameStd.BorderRadius = 1;
            this.firstNameStd.BorderThickness = 2;
            this.firstNameStd.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.firstNameStd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.firstNameStd.DefaultFont = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.firstNameStd.DefaultText = "";
            this.firstNameStd.FillColor = System.Drawing.Color.SlateGray;
            this.firstNameStd.ForeColor = System.Drawing.Color.Transparent;
            this.firstNameStd.HideSelection = true;
            this.firstNameStd.IconLeft = null;
            this.firstNameStd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.firstNameStd.IconPadding = 10;
            this.firstNameStd.IconRight = null;
            this.firstNameStd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.firstNameStd.Lines = new string[0];
            this.firstNameStd.Location = new System.Drawing.Point(29, 165);
            this.firstNameStd.MaxLength = 32767;
            this.firstNameStd.MinimumSize = new System.Drawing.Size(100, 35);
            this.firstNameStd.Modified = false;
            this.firstNameStd.Multiline = false;
            this.firstNameStd.Name = "firstNameStd";
            stateProperties5.BorderColor = System.Drawing.Color.Salmon;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstNameStd.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.SlateGray;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.firstNameStd.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Salmon;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstNameStd.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.LightSteelBlue;
            stateProperties8.FillColor = System.Drawing.Color.SlateGray;
            stateProperties8.ForeColor = System.Drawing.Color.Transparent;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstNameStd.OnIdleState = stateProperties8;
            this.firstNameStd.PasswordChar = '\0';
            this.firstNameStd.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.firstNameStd.PlaceholderText = "First Name";
            this.firstNameStd.ReadOnly = false;
            this.firstNameStd.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.firstNameStd.SelectedText = "";
            this.firstNameStd.SelectionLength = 0;
            this.firstNameStd.SelectionStart = 0;
            this.firstNameStd.ShortcutsEnabled = true;
            this.firstNameStd.Size = new System.Drawing.Size(252, 35);
            this.firstNameStd.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.firstNameStd.TabIndex = 11;
            this.firstNameStd.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.firstNameStd.TextMarginBottom = 0;
            this.firstNameStd.TextMarginLeft = 5;
            this.firstNameStd.TextMarginTop = 0;
            this.firstNameStd.TextPlaceholder = "First Name";
            this.firstNameStd.UseSystemPasswordChar = false;
            this.firstNameStd.WordWrap = true;
            // 
            // addressStd
            // 
            this.addressStd.AcceptsReturn = false;
            this.addressStd.AcceptsTab = false;
            this.addressStd.AnimationSpeed = 200;
            this.addressStd.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addressStd.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addressStd.BackColor = System.Drawing.Color.SlateGray;
            this.addressStd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addressStd.BackgroundImage")));
            this.addressStd.BorderColorActive = System.Drawing.Color.Salmon;
            this.addressStd.BorderColorDisabled = System.Drawing.Color.SlateGray;
            this.addressStd.BorderColorHover = System.Drawing.Color.Salmon;
            this.addressStd.BorderColorIdle = System.Drawing.Color.LightSteelBlue;
            this.addressStd.BorderRadius = 1;
            this.addressStd.BorderThickness = 2;
            this.addressStd.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addressStd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addressStd.DefaultFont = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addressStd.DefaultText = "";
            this.addressStd.FillColor = System.Drawing.Color.SlateGray;
            this.addressStd.ForeColor = System.Drawing.Color.Transparent;
            this.addressStd.HideSelection = true;
            this.addressStd.IconLeft = null;
            this.addressStd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.addressStd.IconPadding = 10;
            this.addressStd.IconRight = null;
            this.addressStd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.addressStd.Lines = new string[0];
            this.addressStd.Location = new System.Drawing.Point(312, 273);
            this.addressStd.MaxLength = 32767;
            this.addressStd.MinimumSize = new System.Drawing.Size(100, 35);
            this.addressStd.Modified = false;
            this.addressStd.Multiline = false;
            this.addressStd.Name = "addressStd";
            stateProperties9.BorderColor = System.Drawing.Color.Salmon;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressStd.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.SlateGray;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addressStd.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Salmon;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressStd.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.LightSteelBlue;
            stateProperties12.FillColor = System.Drawing.Color.SlateGray;
            stateProperties12.ForeColor = System.Drawing.Color.Transparent;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressStd.OnIdleState = stateProperties12;
            this.addressStd.PasswordChar = '\0';
            this.addressStd.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addressStd.PlaceholderText = "Address";
            this.addressStd.ReadOnly = false;
            this.addressStd.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addressStd.SelectedText = "";
            this.addressStd.SelectionLength = 0;
            this.addressStd.SelectionStart = 0;
            this.addressStd.ShortcutsEnabled = true;
            this.addressStd.Size = new System.Drawing.Size(252, 35);
            this.addressStd.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.addressStd.TabIndex = 11;
            this.addressStd.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addressStd.TextMarginBottom = 0;
            this.addressStd.TextMarginLeft = 5;
            this.addressStd.TextMarginTop = 0;
            this.addressStd.TextPlaceholder = "Address";
            this.addressStd.UseSystemPasswordChar = false;
            this.addressStd.WordWrap = true;
            // 
            // contactStd
            // 
            this.contactStd.AcceptsReturn = false;
            this.contactStd.AcceptsTab = false;
            this.contactStd.AnimationSpeed = 200;
            this.contactStd.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.contactStd.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.contactStd.BackColor = System.Drawing.Color.SlateGray;
            this.contactStd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("contactStd.BackgroundImage")));
            this.contactStd.BorderColorActive = System.Drawing.Color.Salmon;
            this.contactStd.BorderColorDisabled = System.Drawing.Color.SlateGray;
            this.contactStd.BorderColorHover = System.Drawing.Color.Salmon;
            this.contactStd.BorderColorIdle = System.Drawing.Color.LightSteelBlue;
            this.contactStd.BorderRadius = 1;
            this.contactStd.BorderThickness = 2;
            this.contactStd.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.contactStd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.contactStd.DefaultFont = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.contactStd.DefaultText = "";
            this.contactStd.FillColor = System.Drawing.Color.SlateGray;
            this.contactStd.ForeColor = System.Drawing.Color.Transparent;
            this.contactStd.HideSelection = true;
            this.contactStd.IconLeft = null;
            this.contactStd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.contactStd.IconPadding = 10;
            this.contactStd.IconRight = null;
            this.contactStd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.contactStd.Lines = new string[0];
            this.contactStd.Location = new System.Drawing.Point(29, 273);
            this.contactStd.MaxLength = 32767;
            this.contactStd.MinimumSize = new System.Drawing.Size(100, 35);
            this.contactStd.Modified = false;
            this.contactStd.Multiline = false;
            this.contactStd.Name = "contactStd";
            stateProperties13.BorderColor = System.Drawing.Color.Salmon;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.contactStd.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.SlateGray;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.contactStd.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Salmon;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.contactStd.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.LightSteelBlue;
            stateProperties16.FillColor = System.Drawing.Color.SlateGray;
            stateProperties16.ForeColor = System.Drawing.Color.Transparent;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.contactStd.OnIdleState = stateProperties16;
            this.contactStd.PasswordChar = '\0';
            this.contactStd.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.contactStd.PlaceholderText = "Contact No#";
            this.contactStd.ReadOnly = false;
            this.contactStd.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.contactStd.SelectedText = "";
            this.contactStd.SelectionLength = 0;
            this.contactStd.SelectionStart = 0;
            this.contactStd.ShortcutsEnabled = true;
            this.contactStd.Size = new System.Drawing.Size(252, 35);
            this.contactStd.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.contactStd.TabIndex = 11;
            this.contactStd.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.contactStd.TextMarginBottom = 0;
            this.contactStd.TextMarginLeft = 5;
            this.contactStd.TextMarginTop = 0;
            this.contactStd.TextPlaceholder = "Contact No#";
            this.contactStd.UseSystemPasswordChar = false;
            this.contactStd.WordWrap = true;
            // 
            // ageStd
            // 
            this.ageStd.AcceptsReturn = false;
            this.ageStd.AcceptsTab = false;
            this.ageStd.AnimationSpeed = 200;
            this.ageStd.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ageStd.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ageStd.BackColor = System.Drawing.Color.SlateGray;
            this.ageStd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ageStd.BackgroundImage")));
            this.ageStd.BorderColorActive = System.Drawing.Color.Salmon;
            this.ageStd.BorderColorDisabled = System.Drawing.Color.SlateGray;
            this.ageStd.BorderColorHover = System.Drawing.Color.Salmon;
            this.ageStd.BorderColorIdle = System.Drawing.Color.LightSteelBlue;
            this.ageStd.BorderRadius = 1;
            this.ageStd.BorderThickness = 2;
            this.ageStd.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ageStd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ageStd.DefaultFont = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ageStd.DefaultText = "";
            this.ageStd.FillColor = System.Drawing.Color.SlateGray;
            this.ageStd.ForeColor = System.Drawing.Color.Transparent;
            this.ageStd.HideSelection = true;
            this.ageStd.IconLeft = null;
            this.ageStd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ageStd.IconPadding = 10;
            this.ageStd.IconRight = null;
            this.ageStd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ageStd.Lines = new string[0];
            this.ageStd.Location = new System.Drawing.Point(312, 220);
            this.ageStd.MaxLength = 32767;
            this.ageStd.MinimumSize = new System.Drawing.Size(100, 35);
            this.ageStd.Modified = false;
            this.ageStd.Multiline = false;
            this.ageStd.Name = "ageStd";
            stateProperties17.BorderColor = System.Drawing.Color.Salmon;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ageStd.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.SlateGray;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ageStd.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.Salmon;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ageStd.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.LightSteelBlue;
            stateProperties20.FillColor = System.Drawing.Color.SlateGray;
            stateProperties20.ForeColor = System.Drawing.Color.Transparent;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ageStd.OnIdleState = stateProperties20;
            this.ageStd.PasswordChar = '\0';
            this.ageStd.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ageStd.PlaceholderText = "Age";
            this.ageStd.ReadOnly = false;
            this.ageStd.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ageStd.SelectedText = "";
            this.ageStd.SelectionLength = 0;
            this.ageStd.SelectionStart = 0;
            this.ageStd.ShortcutsEnabled = true;
            this.ageStd.Size = new System.Drawing.Size(252, 35);
            this.ageStd.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.ageStd.TabIndex = 11;
            this.ageStd.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ageStd.TextMarginBottom = 0;
            this.ageStd.TextMarginLeft = 5;
            this.ageStd.TextMarginTop = 0;
            this.ageStd.TextPlaceholder = "Age";
            this.ageStd.UseSystemPasswordChar = false;
            this.ageStd.WordWrap = true;
            // 
            // lastNameStd
            // 
            this.lastNameStd.AcceptsReturn = false;
            this.lastNameStd.AcceptsTab = false;
            this.lastNameStd.AnimationSpeed = 200;
            this.lastNameStd.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.lastNameStd.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.lastNameStd.BackColor = System.Drawing.Color.SlateGray;
            this.lastNameStd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("lastNameStd.BackgroundImage")));
            this.lastNameStd.BorderColorActive = System.Drawing.Color.Salmon;
            this.lastNameStd.BorderColorDisabled = System.Drawing.Color.SlateGray;
            this.lastNameStd.BorderColorHover = System.Drawing.Color.Salmon;
            this.lastNameStd.BorderColorIdle = System.Drawing.Color.LightSteelBlue;
            this.lastNameStd.BorderRadius = 1;
            this.lastNameStd.BorderThickness = 2;
            this.lastNameStd.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.lastNameStd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.lastNameStd.DefaultFont = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lastNameStd.DefaultText = "";
            this.lastNameStd.FillColor = System.Drawing.Color.SlateGray;
            this.lastNameStd.ForeColor = System.Drawing.Color.Transparent;
            this.lastNameStd.HideSelection = true;
            this.lastNameStd.IconLeft = null;
            this.lastNameStd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.lastNameStd.IconPadding = 10;
            this.lastNameStd.IconRight = null;
            this.lastNameStd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.lastNameStd.Lines = new string[0];
            this.lastNameStd.Location = new System.Drawing.Point(312, 165);
            this.lastNameStd.MaxLength = 32767;
            this.lastNameStd.MinimumSize = new System.Drawing.Size(100, 35);
            this.lastNameStd.Modified = false;
            this.lastNameStd.Multiline = false;
            this.lastNameStd.Name = "lastNameStd";
            stateProperties21.BorderColor = System.Drawing.Color.Salmon;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameStd.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.SlateGray;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.Empty;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.lastNameStd.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.Salmon;
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameStd.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.LightSteelBlue;
            stateProperties24.FillColor = System.Drawing.Color.SlateGray;
            stateProperties24.ForeColor = System.Drawing.Color.Transparent;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameStd.OnIdleState = stateProperties24;
            this.lastNameStd.PasswordChar = '\0';
            this.lastNameStd.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.lastNameStd.PlaceholderText = "Last Name";
            this.lastNameStd.ReadOnly = false;
            this.lastNameStd.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.lastNameStd.SelectedText = "";
            this.lastNameStd.SelectionLength = 0;
            this.lastNameStd.SelectionStart = 0;
            this.lastNameStd.ShortcutsEnabled = true;
            this.lastNameStd.Size = new System.Drawing.Size(252, 35);
            this.lastNameStd.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.lastNameStd.TabIndex = 11;
            this.lastNameStd.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.lastNameStd.TextMarginBottom = 0;
            this.lastNameStd.TextMarginLeft = 5;
            this.lastNameStd.TextMarginTop = 0;
            this.lastNameStd.TextPlaceholder = "Last Name";
            this.lastNameStd.UseSystemPasswordChar = false;
            this.lastNameStd.WordWrap = true;
            // 
            // fatherNameStd
            // 
            this.fatherNameStd.AcceptsReturn = false;
            this.fatherNameStd.AcceptsTab = false;
            this.fatherNameStd.AnimationSpeed = 200;
            this.fatherNameStd.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.fatherNameStd.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.fatherNameStd.BackColor = System.Drawing.Color.SlateGray;
            this.fatherNameStd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("fatherNameStd.BackgroundImage")));
            this.fatherNameStd.BorderColorActive = System.Drawing.Color.Salmon;
            this.fatherNameStd.BorderColorDisabled = System.Drawing.Color.SlateGray;
            this.fatherNameStd.BorderColorHover = System.Drawing.Color.Salmon;
            this.fatherNameStd.BorderColorIdle = System.Drawing.Color.LightSteelBlue;
            this.fatherNameStd.BorderRadius = 1;
            this.fatherNameStd.BorderThickness = 2;
            this.fatherNameStd.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.fatherNameStd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.fatherNameStd.DefaultFont = new System.Drawing.Font("Palatino Linotype", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.fatherNameStd.DefaultText = "";
            this.fatherNameStd.FillColor = System.Drawing.Color.SlateGray;
            this.fatherNameStd.ForeColor = System.Drawing.Color.Transparent;
            this.fatherNameStd.HideSelection = true;
            this.fatherNameStd.IconLeft = null;
            this.fatherNameStd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.fatherNameStd.IconPadding = 10;
            this.fatherNameStd.IconRight = null;
            this.fatherNameStd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.fatherNameStd.Lines = new string[0];
            this.fatherNameStd.Location = new System.Drawing.Point(29, 220);
            this.fatherNameStd.MaxLength = 32767;
            this.fatherNameStd.MinimumSize = new System.Drawing.Size(100, 35);
            this.fatherNameStd.Modified = false;
            this.fatherNameStd.Multiline = false;
            this.fatherNameStd.Name = "fatherNameStd";
            stateProperties25.BorderColor = System.Drawing.Color.Salmon;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.fatherNameStd.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.SlateGray;
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.Empty;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.fatherNameStd.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.Salmon;
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.fatherNameStd.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.LightSteelBlue;
            stateProperties28.FillColor = System.Drawing.Color.SlateGray;
            stateProperties28.ForeColor = System.Drawing.Color.Transparent;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.fatherNameStd.OnIdleState = stateProperties28;
            this.fatherNameStd.PasswordChar = '\0';
            this.fatherNameStd.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.fatherNameStd.PlaceholderText = "Father\'s Name";
            this.fatherNameStd.ReadOnly = false;
            this.fatherNameStd.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.fatherNameStd.SelectedText = "";
            this.fatherNameStd.SelectionLength = 0;
            this.fatherNameStd.SelectionStart = 0;
            this.fatherNameStd.ShortcutsEnabled = true;
            this.fatherNameStd.Size = new System.Drawing.Size(252, 35);
            this.fatherNameStd.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.fatherNameStd.TabIndex = 11;
            this.fatherNameStd.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.fatherNameStd.TextMarginBottom = 0;
            this.fatherNameStd.TextMarginLeft = 5;
            this.fatherNameStd.TextMarginTop = 0;
            this.fatherNameStd.TextPlaceholder = "Father\'s Name";
            this.fatherNameStd.UseSystemPasswordChar = false;
            this.fatherNameStd.WordWrap = true;
            // 
            // Student_Form
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(679, 667);
            this.Controls.Add(this.registerUser);
            this.Name = "Student_Form";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Student_Form";
            this.Load += new System.EventHandler(this.Student_Form_Load);
            this.registerUser.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel registerUser;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton exit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton addStudent;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox firstNameStd;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox addressStd;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox contactStd;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox ageStd;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox lastNameStd;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox fatherNameStd;
        private System.Windows.Forms.RadioButton femaleRadioBtn;
        private System.Windows.Forms.RadioButton maleRadioBtn;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.ComboBox courseBox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton courseBtn;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox courseText;
        private System.Windows.Forms.ComboBox semesterBox;
        private System.Windows.Forms.Label stdListFormLbl;
    }
}